name: pmd
on: [push]
jobs:
  pmd_job:
    runs-on: ubuntu-latest
    name: PMD job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run PMD
      uses: kemsakurai/action-pmd@master
      with:
        reporter: 'github-pr-review'
        tool_name: 'pmd_reviewdog'
